apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment-backend
  template:
    metadata:
      labels:
        app: assignment-backend
    spec:
      containers:
      - name: assignment-backend
        image: docker.io/raushik/assignment-backend
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-storage
          mountPath: /app/data
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: assignment-backend
spec:
  selector:
    app: assignment-backend
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: /mnt/backend-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi
